name: Tarea
on:
  push:
    branches:
      - test_1
jobs:
  print_messages:
    runs-on: ubuntu-latest
    steps:
        run: echo "Impresión 1"
        run: echo "Impresión 2"
        run: echo "Impresión 3"